version: "3.2"
services:
  prometheus:
    image: prom/prometheus:v2.1.0
    ports:
      - 9090:9090/tcp
    volumes:
      - ./mount/prometheus:/etc/prometheus

  alertmanager:
    image: prom/alertmanager:v0.13.0
    ports:
      - "9093:9093"
    volumes:
      - ./mount/alertmanager:/etc/alertmanager
    links:
      - prometheus

  grafana:
    image: grafana/grafana:4.6.3
    ports:
      - 3000:3000/tcp
    volumes:
      - ".mount/grafana/:/var/lib/grafana"
    links:
      - prometheus
