version: "3.2"
services:
  zookeeper:
    build: ./zookeeper
    container_name: zookeeper
    command:
      - "start-foreground"
    ports:
      - "2181:2181"
    networks:
      prom_net:
        ipv4_address: 10.5.0.2

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    links:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=localhost
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_BROKER_ID=1
      - KAFKA_CREATE_TOPICS=customer:5:1,audit:5:1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - JMX_PORT=9999
    networks:
      prom_net:
        ipv4_address: 10.5.0.3

  kafka-jmx-exporter:
    build: ./prometheus-jmx-exporter
    container_name: kafka_jmx_exporter
    ports:
      - "8080:8080"
    links:
      - kafka
    environment:
      - JMX_PORT=9999
      - JMX_HOST=kafka
      - HTTP_PORT=8080
      - JMX_EXPORTER_CONFIG_FILE=kafka.yml
    networks:
      prom_net:
        ipv4_address: 10.5.0.4

  prometheus1:
    ports:
      - 9090:9090/tcp
    mac_address: 00:00:00:00:00:01
    image: prom/prometheus:master
    container_name: prometheus1
    volumes:
      - ./mount/prometheus:/etc/prometheus
    networks:
      prom_net:
        ipv4_address: 10.5.0.5
    links:
      - kafka-jmx-exporter
    command:
      - '--log.level=debug'
      - '--config.file=/etc/prometheus/prometheus.yml'

  # prometheus2:
  #   ports:
  #     - 9091:9090/tcp
  #   mac_address: 00:00:00:00:00:02
  #   image: prom/prometheus:master
  #   volumes:
  #     - ./mount/prometheus:/etc/prometheus
  #   networks:
  #     prom_net:
  #       ipv4_address: 10.5.0.6
  #   links:
  #     - kafka-jmx-exporter

  alertmanager1:
    ports:
      - "9093:9093"
    mac_address: 00:00:00:00:00:03
    image: prom/alertmanager:master
    container_name: alertmanager1
    volumes:
      - ./mount/alertmanager:/etc/alertmanager
    links:
      - prometheus1
#      - prometheus2
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
      # - '--mesh.peer=10.5.0.8:7000'
      # - '--mesh.listen-address=0.0.0.0:7000'
      # - '--mesh.nickname=am2'
      - '--log.level=debug'
    networks:
      prom_net:
        ipv4_address: 10.5.0.7

  # alertmanager2:
  #   ports:
  #     - "9094:9093"
  #   mac_address: 00:00:00:00:00:04
  #   image: prom/alertmanager:master
  #   volumes:
  #     - ./mount/alertmanager:/etc/alertmanager
  #   links:
  #     - prometheus1
  #     - prometheus2
  #   command:
  #     - '--config.file=/etc/alertmanager/config.yml'
  #     - '--storage.path=/alertmanager'
  #     # - '--mesh.peer=10.5.0.7:7000'
  #     # - '--mesh.listen-address=0.0.0.0:7000'
  #     # - '--mesh.nickname=am2'
  #     - '--log.level=debug'
  #   networks:
  #     prom_net:
  #       ipv4_address: 10.5.0.8

  grafana:
    image: grafana/grafana:4.6.3
    container_name: grafana
    ports:
      - 3000:3000/tcp
    links:
      - prometheus1
    networks:
      prom_net:
        ipv4_address: 10.5.0.9
    volumes:
      - "graf-db:/var/lib/grafana"

  unsee:
    image: cloudflare/unsee:latest
    container_name: unsee
    ports:
      - 10000:8080
    links:
      - alertmanager1
    command:
      - '/unsee'
    environment:
      - ALERTMANAGER_URI=http://10.5.0.7:9093
      - LOG_LEVEL=debug
    networks:
      prom_net:
        ipv4_address: 10.5.0.10

networks:
  prom_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.5.0.0/16

volumes:
 graf-db:
